sudo: required
language: python
python:
- "3.6"
services:
- docker
before_install:
- docker build -t aurman_docker .
script:
- docker run aurman_docker unit_tests.test_split_query_helper
- docker run aurman_docker unit_tests.test_parse_pacman_args
- docker run aurman_docker docker_tests.install_tests
- docker run aurman_docker docker_tests.cache_tests
- docker run aurman_docker docker_tests.build_dir_tests
- docker run aurman_docker docker_tests.testing_repo_tests
- docker run aurman_docker docker_tests.pkgdest_tests
- docker run aurman_docker docker_tests.archive_tests
notifications:
  email: false
